### ISSUE TITLE
Add multiple links separated by commas

### ISSUE THREAD

**Issue by LunarMarathon** [LunarMarathon/graphToTable#1]
Currently only one - one node connections can be made - 
![image](https://user-images.githubusercontent.com/113847439/195141628-d6895bdc-edf2-4084-8a3d-914a2bff4880.png)
Allow multiple nodes to be added - 
![image](https://user-images.githubusercontent.com/113847439/195141692-16c420ca-a72a-43e9-a96c-f8e319bc413d.png)

**Comment by Ansh1693** [comment]
Can you assign me this issue?
I have gone through all the files.

**Comment by LunarMarathon** [comment]
Awesome, I've assigned it to you, thank you for showing interest :)

**Comment by LunarMarathon** [comment]
@Ansh1693 Hey, I noticed that you closed the PR without any comments, are you still working on this?

**Comment by Ansh1693** [comment]
Yes I am working on it. Will update in 10-12 hours as I am attending a workshop

**Comment by LunarMarathon** [comment]
Ok, no issues, just wanted to confirm

**Comment by Ansh1693** [comment]
![image](https://user-images.githubusercontent.com/72507723/196021885-5387a381-e570-45ed-ad52-7b2c53b9e20e.png)
![image](https://user-images.githubusercontent.com/72507723/196021889-c50faad1-a1bc-4aad-b186-b683f7f7f35b.png)
![image](https://user-images.githubusercontent.com/72507723/196021895-373e473a-bb85-4bd0-a1ef-b8bcecb1e0a6.png)
![image](https://user-images.githubusercontent.com/72507723/196021899-bcc4e9f3-1422-44d5-953d-5c75ed497ab4.png)
![image](https://user-images.githubusercontent.com/72507723/196021904-1d72eb50-0dc1-4c6b-a2d9-9d5cfe3864f7.png)
![image](https://user-images.githubusercontent.com/72507723/196021906-18cf449d-85cb-47e9-85ac-c69ce5d781f9.png)

**Comment by Ansh1693** [comment]
Hey man, pls have a look of issues you pointed out!!
I Believe that I have fixed it

**Comment by LunarMarathon** [comment]
You have! Thanks again!

**Comment by Ansh1693** [comment]
You are welcome  man!!!
