### ISSUE TITLE
Addition of auto scroll button when the table becomes large.

### ISSUE THREAD

**Issue by yashjoshi-dotcom** [LunarMarathon/graphToTable#10]
Problem :Just noticed your site and saw that in case of large tables we have to scroll a lot to go to the top of the page again to perform any task.

Proposed Solution: I Can add an auto scroll to the top button on the bottom right corner of the site with its theme matching with that of the site.

Screenshot for Reference: 
![image](https://user-images.githubusercontent.com/77540753/195242923-4aa36292-938d-49a9-ab78-f0407fb5bb4d.png)

**Comment by LunarMarathon** [comment]
This would be great! Please use one of the colors in root selector for now. I'll change the whole palette later. Assigned it to you!
