### ISSUE TITLE
Sort option 

### ISSUE THREAD

**Issue by LunarMarathon** [LunarMarathon/graphToTable#15]
Sort the rows by minimum number of nodes(cells) and maximum no. of nodes(cells)

**Comment by Swathi-L** [comment]
Hi @LunarMarathon, can I work on this issue? If yes, could you assign it to me?

**Comment by Swathi-L** [comment]
Hi @LunarMarathon, can I work on this? If yes, could you assign it to me?

**Comment by LunarMarathon** [comment]
@Swathi-L Done. I hope you've gone through the code. All the best!

**Comment by Swathi-L** [comment]
@LunarMarathon, do I add a new button to sort or by default display rows in sorted order whenever table is generated?

**Comment by LunarMarathon** [comment]
2 new buttons, add them after the download csv one for now (I'll put few buttons under some advanced section later) "Sort by min nodes" "Sort by max nodes"

Also, please don't format the code or if needed only format your lines of code as it gets difficult when I have to review.

**Comment by Swathi-L** [comment]
@LunarMarathon, I have raised pull request, https://github.com/LunarMarathon/graphToTable/pull/49
please review it.
