### ISSUE TITLE
Make UI Improvements

### ISSUE THREAD

**Issue by Athithya-t** [LunarMarathon/graphToTable#17]
I would like to improve the UI of the page.
Can you assign me to this issue?

**Comment by LunarMarathon** [comment]
What changes specifically? I'm focusing on functionality at the moment, if your suggestions are something I need now, I can assign it to you

**Comment by Athithya-t** [comment]
Change the color of the buttons and title. Make the "Generate table" button look more prominent.

**Comment by AshwinHebbar314** [comment]
Hey, I'd like to work on this. Please assign it to me

**Comment by AshwinHebbar314** [comment]
I'll simplify the UI, make it look pretty and what not...

**Comment by LunarMarathon** [comment]
Hey, the final design for the site has not yet been finalized so I'm not looking for enhancements at the moment other than the ones I'm listing as they're encountered. Please look at open issues and see if you'd like to contribute. Thanks for showing interest 😄
