### ISSUE TITLE
Fix Clear screen issue

### ISSUE THREAD

**Issue by nileshlad09** [LunarMarathon/graphToTable#18]
![Screenshot_2022-10-12-22-20-09-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/89249015/195402353-73900f95-8b8f-4437-9c13-5b36496bad1f.jpg)

Even after a clear screen, the div is there we can remove it after clicking on the clear screen and I can improve the button styling 
Please assign this issue to me @LunarMarathon

**Comment by LunarMarathon** [comment]
Hey, there were a few dynamic changes I had planned to do along with this one, which I could merge w/o breaking anything else (phew!) 

So, this one is done. I'll assign another one to you

**Comment by LunarMarathon** [comment]
Would you like to work on #22 ?

**Comment by nileshlad09** [comment]
Ok assign this one

**Comment by LunarMarathon** [comment]
Can you comment on that issue, you're not appearing in the dropdown to assign
