### ISSUE TITLE
dark Mode button needed

### ISSUE THREAD

**Issue by ElvinPero** [LunarMarathon/graphToTable#20]
Every site  needs a dark mode today
@LunarMarathon Assign me tis

**Comment by ElvinPero** [comment]
![image](https://user-images.githubusercontent.com/101408574/195414987-6fc6107a-f46e-43c1-9dba-644010d9ffc5.png)
@LunarMarathon This will be my work

**Comment by LunarMarathon** [comment]
Hey, there are 6-7 colors used right now, roughly how many will be used in dark mode? And there are hyperlinks now, and the text bg for checked check-boxes changes too. Please consider those and let me know. Or you can start and I'll suggest the changes that time

**Comment by ElvinPero** [comment]
@LunarMarathon I will work according to that

**Comment by ElvinPero** [comment]
@LunarMarathon Also add hacktober label for the issue. working on changes

**Comment by ElvinPero** [comment]
You can assign this issue to me

**Comment by LunarMarathon** [comment]
Done, all the best :)

**Comment by ElvinPero** [comment]
@LunarMarathon I have implemented dark mode
