### ISSUE TITLE
Proposal to add project contributors details in readme file.

### ISSUE THREAD

**Issue by aritroo** [LunarMarathon/graphToTable#21]
Hi @LunarMarathon 

What about adding the project contributor's details in footer of readme file??? 
Please assign me for this issue . I want to work on it. Hope you will like it.🙂

**Comment by LunarMarathon** [comment]
Hi, how will it be? will the contributors be added dynamically?

**Comment by aritroo** [comment]
> Hi, how will it be? will the contributors be added dynamically?

Yes ...U can see this picture for reference.


![Screenshot_2022-10-13-16-29-16-30_320a9a695de7cdce83ed5281148d6f19.jpg](https://user-images.githubusercontent.com/91552411/195579515-6ebc9974-9884-4af8-8251-37ab2a88d304.jpg)

**Comment by LunarMarathon** [comment]
Great, I hope the contributors' names need not be added manually each time a contributor contributes

**Comment by aritroo** [comment]
> Great, I hope the contributors' names need not be added manually each time a contributor contributes

Sure ... please assign me for hacktoberfest 2022

**Comment by LunarMarathon** [comment]
Done!
