### ISSUE TITLE
Align the table that's generated to the center

### ISSUE THREAD

**Issue by LunarMarathon** [LunarMarathon/graphToTable#22]
This is how it is right now:
![image](https://user-images.githubusercontent.com/113847439/195419308-e8f41a3a-4ecd-4b56-91c2-17f5ee4afc6a.png)

Please make the same alignment changes for the table that's generated by the search button as well

**Comment by LunarMarathon** [comment]
@nileshlad09

**Comment by nileshlad09** [comment]
Hey assign this to me @LunarMarathon

**Comment by LunarMarathon** [comment]
Done!

**Comment by nileshlad09** [comment]
![image](https://user-images.githubusercontent.com/89249015/195636860-677b3ae9-46fb-4c1d-a6b2-1502b8217e57.png)

@LunarMarathon is this ok?

**Comment by LunarMarathon** [comment]
Hey, I meant this ;-;
![image](https://user-images.githubusercontent.com/113847439/195662409-15fa30c7-1885-44dc-ba0e-f85d4225f0c0.png)

Let the table itself come to the center, let the rows and content be as it is (left aligned). Please don't give it a width, it'll look just like the outer teal colored container then. When more content is added, let it become wider just like it does already. Please let me know if you have any doubts

**Comment by nileshlad09** [comment]
Ok I do it

**Comment by nileshlad09** [comment]
![IMG20221014141938_01](https://user-images.githubusercontent.com/89249015/195804969-4a35aff2-53ee-4771-af87-295b875b08e6.jpg)


Is this ok ? @LunarMarathon

**Comment by LunarMarathon** [comment]
Yep, that's great, you can open a PR

**Comment by nileshlad09** [comment]
Ok
