### ISSUE TITLE
Keep checkboxes on the same line as text

### ISSUE THREAD

**Issue by LunarMarathon** [LunarMarathon/graphToTable#3]
Sometimes the text goes underneath like this
![image](https://user-images.githubusercontent.com/113847439/195142412-34d62a81-fdf6-424a-bacb-51c0438cd6ae.png)
make changes to avoid that

**Comment by Yasshu55** [comment]
i would like to work on this issue

**Comment by LunarMarathon** [comment]
Assigned it to you

**Comment by LunarMarathon** [comment]
![image](https://user-images.githubusercontent.com/113847439/195578609-64a13535-fe9a-4538-99df-b65bd242257c.png)

Closed~
