### ISSUE TITLE
Atualizar readme.md

### ISSUE THREAD

**Issue by BrunoLagoa** [LunarMarathon/graphToTable#30]
Hello, I would like to update the readme, add the mock gives running application and text. If it makes sense, you can assign me this issue.

![mockup](https://user-images.githubusercontent.com/3878945/195602860-1b5dd556-7eba-43c0-94d7-6bb2dd644094.jpg)

**Comment by LunarMarathon** [comment]
Hi, sorry I don't require this addition at the moment. Lots of changes are being made so this would have to be changed often too and I prefer contributors checking the site that's linked instead. Thank you for showing interest! You can check other open issues and see if you'd like to contribute!

**Comment by BrunoLagoa** [comment]
nice
