### ISSUE TITLE
Improving Color scheme of website 

### ISSUE THREAD

**Issue by Siddhesh172004** [LunarMarathon/graphToTable#35]
The Color Scheme can be improved. I can try some of new color scheme on it. 
Kindly assign me this issue

**Comment by ElvinPero** [comment]
@LunarMarathon This issue should be taken care of to add more fuctionality

**Comment by LunarMarathon** [comment]
Hey, I don't require any changes for the light theme at the moment. Thanks for showing interest, if you'd like you can consider contributing to other open issues
