### ISSUE TITLE
Import option

### ISSUE THREAD

**Issue by LunarMarathon** [LunarMarathon/graphToTable#4]
Currently there's only download CSV option. Add an import option

**Comment by S-Parker7000** [comment]
Please assign me this

**Comment by LunarMarathon** [comment]
Done, good luck!

**Comment by Aditi-1709** [comment]
Please assign me this issue !

**Comment by Aditi-1709** [comment]
Please add the label of hacktoberfest-accepted on this issue so that I'll commit and push my changes.

**Comment by LunarMarathon** [comment]
I've assigned it to you. Yeah, I'll add that to the PR. Good luck!
