### ISSUE TITLE
Align the 2 inputs to the center

### ISSUE THREAD

**Issue by LunarMarathon** [LunarMarathon/graphToTable#5]
They are currently on the left

**Comment by Yasshu55** [comment]
i would like to work on this issue please assign me under hacktoberfest

**Comment by LunarMarathon** [comment]
Assigned it to you

**Comment by Siddhesh172004** [comment]
I like to work on this issue kindly  please assign it to me

**Comment by LunarMarathon** [comment]
@Siddhesh172004 Hey, the issue has already been assigned to @Yasshu55 . Please pick unassigned issues and request for assignment first so that more than one person doesn't have to work on the same issue. I'll consider your PR if I don't hear from @Yasshu55 in 2-3 days or if they wish to unassign themselves. 

Do check the other issues and see if you'd like to contribute! Thanks for showing interest~
