### ISSUE TITLE
ADDITION OF IMAGES OF OCEANS LINKING TO THEIR INFORMATION

### ISSUE THREAD

**Issue by Swastik200** [LunarMarathon/graphToTable#7]
VIA SHORT VIDEO I WILL LINK THEM
HOPE IT IS A COOL IDEA

**Comment by LunarMarathon** [comment]
Can you please explain further and how you plan to do it? Is it web scraping for each node or how is it?

**Comment by Swastik200** [comment]
Just simple sir
Using map coordinates of each oceans and linking to their respective video
links
Simple html and css

**Comment by LunarMarathon** [comment]
Oh, the table content is actually dummy content. It's just used as an example. The user can add anything to the table so having just this for oceans would be weird. If it's dynamic for all nodes added that would be better. So, this won't do, sorry. 

Please check other issues if you'd like to contribute, thanks for showing interest!

**Comment by Swastik200** [comment]
Thank you for the clarification.
